# This is a basic workflow to help you get started with Actions

name: Java CI with Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ets

    steps:
    - uses: actions/checkout@v2
    
    ####   
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.5.4
        
    - name: Build with MVN
      run: mvn clean test --file rdr-service/pom.xml
      
    - name: Test Reporter
  # You may pin to the exact commit or the version.
  # uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1
      uses: dorny/test-reporter@v1.5.0
      with:
    # Name or regex of artifact containing test results
    # Name of the check run
       name: Test Run
       path: "**/surefire-reports/TEST-*.xml"
       reporter: java-junit 
